version: "3"

services:
  mesa:
    container_name: mc-edge
    user: "${UID}:${GID}"
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
      - "./plugins/1.16.1:/data/plugins"
      - "./assets:/data/assets"
    environment:
      OVERRIDE_SERVER_PROPERTIES: "true"
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "1500M"
      SERVER_NAME: "MESA"
      SERVER_PORT: 25565
      MOTD: "Check ServerListPlus plugin"
      TYPE: "PAPER"
      VERSION: "1.16.1"
      OPS: "purplepant1es"
      ICON: "/data/assets/server-icon.png"
      MAX_PLAYERS: "10"
      DIFFICULTY: "normal"
      MODE: "survival"
      VIEW_DISTANCE: 6
      FORCE_GAMEMODE: "true"
      ALLOW_NETHER: "true"
      HARDCORE: "false"
      SNOOPER_ENABLED: "false"
      PVP: "false"
      LEVEL_TYPE: "default"
      LEVEL: "world"

      SPAWN_PROTECTION: 0
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENABLE_COMMAND_BLOCK: "true"
      GENERATE_STRUCTURES: "true"
      MAX_BUILD_HEIGHT: 256
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"

      CONSOLE: "true"
      #ENABLE_RCON: "true"
      #RCON_PASSWORD: "testingpw"
      #RCON_PORT: 28016
    restart: always
    #  mc-rcon:
    #container_name: "mc-rcon"
    #image: itzg/rcon
    #ports:
    #  - "4326:4326"
    #  - "4327:4327"
    #depends_on:
    #      - "mesa"
    #volumes:
    #      - "rcon:/opt/rcon-web-admin/db"

volumes:
  mc:
  assets:
  plugin:
  rcon:
